version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

formats:
   - pdf
   - epub
   - htmlzip

python:
  install:
    - requirements: docs/requirements.txt